version: "3.8"
services:
  node-app:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - ./:/app
      - /app/node_modules
    env_file:
      - ./.env
    depends_on: 
      - mysql
  mysql:
    image: mysql:8.0
    restart: always
    env_file:
      - ./.env_mysql
    ports:
      - "3306:3306"
